// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace SubSolutionVisualStudio
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string SubSolutionVisualStudioString = "f9791f35-5647-4ee1-8cb6-50fca6c2ebcc";
        public static Guid SubSolutionVisualStudio = new Guid(SubSolutionVisualStudioString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyMenuGroup = 0x0001;
        public const int OpenSubSlnFileCommand = 0x0100;
    }
}