// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace SubSolution.VisualStudio
{
    internal sealed partial class Vsix
    {
        public const string Id = "SubSolution.3bc7a66c-1151-4e36-a52e-e3eb7c4b3ba2";
        public const string Name = "SubSolution (2019)";
        public const string Description = @"Use .subsln files to maintain Visual Studio solutions.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Rémi Morillon";
        public const string Tags = "subsolution subsln solution sln generate configuration";
    }
}
