// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace SubSolution.VisualStudio
{
    internal sealed partial class Vsix
    {
        public const string Id = "SubSolution.bc8d282e-9593-4a4a-95eb-faef6b8ed4ce";
        public const string Name = "SubSolution (2022)";
        public const string Description = @"Use .subsln files to maintain Visual Studio solutions.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Rémi Morillon";
        public const string Tags = "subsolution subsln solution sln";
    }
}
