// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace SubSolutionVisualStudio
{
    internal sealed partial class Vsix
    {
        public const string Id = "SubSolutionVisualStudio.0d154545-dfa7-41a5-9e42-2524714fc52a";
        public const string Name = "SubSolution";
        public const string Description = @"Empty VSIX Project.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Rémi Morillon";
        public const string Tags = "";
    }
}
