name: Change
on:
  workflow_dispatch:
  push:
    branches: ['**']
    tags-ignore: ['**']
  pull_request:
    branches: ['**']
    tags-ignore: ['**']
jobs:
  dotnet-validate:
    name: dotnet
    uses: ReMinoer/workflows/.github/workflows/dotnet-validate.yml@master
    with:
      solution_file: SubSolution.Core.sln
      dotnet_version: |
        3.1
        5
  vsix-validate:
    name: vsix
    uses: ReMinoer/workflows/.github/workflows/vsix-validate.yml@master
    with:
      solution_file: SubSolution.sln
      dotnet_version: |
        3.1
        5
