name: Release
on:
  release:
    types: [published]
jobs:
  dotnet-release:
    name: dotnet
    uses: ReMinoer/workflows/.github/workflows/dotnet-release.yml@master
    with:
      solution_file: SubSolution.Core.sln
      project_folder: Sources/SubSolution.CommandLine
      target_framework: net5.0
      zip_prefix: subsln
  vsix-release-2019:
    name: vsix
    uses: ReMinoer/workflows/.github/workflows/vsix-release.yml@master
    with:
      solution_file: SubSolution.sln
      project_folder: Plugins/SubSolution.VisualStudio16
      vsix_name: SubSolution.VisualStudio16
  vsix-release-2022:
    name: vsix
    uses: ReMinoer/workflows/.github/workflows/vsix-release.yml@master
    with:
      solution_file: SubSolution.sln
      project_folder: Plugins/SubSolution.VisualStudio17
      vsix_name: SubSolution.VisualStudio17
  dotnet-nuget:
    needs: dotnet-release
    name: dotnet
    uses: ReMinoer/workflows/.github/workflows/dotnet-nuget.yml@master
    with:
      solution_file: SubSolution.Core.sln
      sources_folder: Sources
    secrets:
      nuget_token: ${{ secrets.NUGET_TOKEN }}
  vsix-publish-2019:
    needs: [vsix-release-2019, vsix-release-2022]
    name: vsix
    uses: ReMinoer/workflows/.github/workflows/vsix-publish.yml@master
    with:
      solution_file: SubSolution.sln
      project_folder: Plugins/SubSolution.VisualStudio16
      vsix_name: SubSolution.VisualStudio16
    secrets:
      marketplace_token: ${{ secrets.MARKETPLACE_TOKEN }}
  vsix-publish-2022:
    needs: [vsix-release-2019, vsix-release-2022]
    name: vsix
    uses: ReMinoer/workflows/.github/workflows/vsix-publish.yml@master
    with:
      solution_file: SubSolution.sln
      project_folder: Plugins/SubSolution.VisualStudio17
      vsix_name: SubSolution.VisualStudio17
    secrets:
      marketplace_token: ${{ secrets.MARKETPLACE_TOKEN }}