name: Release
on:
  release:
    types: [published]
jobs:
  dotnet-release:
    name: dotnet
    uses: ReMinoer/workflows/.github/workflows/dotnet-release.yml@master
    with:
      project_folder: Sources/SubSolution.CommandLine
      target_framework: net5.0
      zip_prefix: subsln
  dotnet-nuget:
    needs: dotnet-release
    name: dotnet
    uses: ReMinoer/workflows/.github/workflows/dotnet-nuget.yml@master
    with:
      sources_folder: Sources
    secrets:
      nuget_token: ${{ secrets.NUGET_TOKEN }}